# Generated by Django 5.1.3 on 2025-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='blank.jpg', upload_to='profile_pics/'),
        ),
    ]
